<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_ConfirmNewPassword</name>
   <tag></tag>
   <elementGuidId>a76e6270-f302-4961-862c-b390650f772c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmNewPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ConfirmNewPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d4f0de4-6ad0-413e-a05c-ed6fffc465e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line password</value>
      <webElementGuid>ad742e6e-472e-4b3f-97a3-9337d2c2409c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>33e9552e-6595-4f44-8a2f-59fdbe275dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>The new password and confirmation password do not match.</value>
      <webElementGuid>42c6ce48-364b-4d19-b483-26ed91f685c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.NewPassword</value>
      <webElementGuid>8925cd9d-6be2-4131-859f-280f4a029a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Password is required.</value>
      <webElementGuid>f5fc0aff-6c5c-402f-ad8c-7738d6a3a320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmNewPassword</value>
      <webElementGuid>dc66e160-b56b-41d1-afc9-67c44f8070be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConfirmNewPassword</value>
      <webElementGuid>12a1b23e-4282-4ef0-91a3-effe77530468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a912c4ab-b984-4f01-be56-6b9b00bffdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmNewPassword&quot;)</value>
      <webElementGuid>6bb14011-b9a2-4408-a343-1da360cda904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmNewPassword']</value>
      <webElementGuid>5552eecd-2716-47ac-9f53-b8eb8fb4781b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/input</value>
      <webElementGuid>95aa71a6-26ee-4bb6-bcaa-e0d85757f69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ConfirmNewPassword' and @name = 'ConfirmNewPassword' and @type = 'password']</value>
      <webElementGuid>385caf3b-9e3e-4d79-98ec-1f4d84ec5370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
