<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Old password_OldPassword</name>
   <tag></tag>
   <elementGuidId>c0b37961-08a1-4a99-8d5e-d678539608ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OldPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OldPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fafc1c77-09dc-4b8a-b68b-dddb73d707fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line password</value>
      <webElementGuid>796b15ff-89a4-4f9e-b63a-d1f9da10d061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a47728b-9ea1-4f2b-99a0-ede67853dbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Old password is required.</value>
      <webElementGuid>af51131c-8409-4914-ac2f-ffa88186003b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OldPassword</value>
      <webElementGuid>1ed3ae72-d548-4eb8-b726-20364a24468d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OldPassword</value>
      <webElementGuid>53e4e87e-02af-48ba-b46f-69533fca7c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ff765ad0-e2ff-4535-90ea-7e9aeb26f697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OldPassword&quot;)</value>
      <webElementGuid>83135b5b-a10c-4aa9-a743-78d64d031ed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OldPassword']</value>
      <webElementGuid>cf71c9ba-b567-4b70-a73f-8bfaad1c6520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>a173f1fe-2e86-4110-82e4-e1f07f9a95cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OldPassword' and @name = 'OldPassword' and @type = 'password']</value>
      <webElementGuid>4dc02a07-b927-44d2-87f0-bbdf13eb9087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
