<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e81ad73b-7ea9-4332-be82-45c9df945a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product-details-form']/div/div/div/div[2]/div/a[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6ad85eee-49ea-4807-8f5c-4932da958263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demowebshop.tricentis.com/content/images/thumbs/0000205_simple-computer_70.jpeg</value>
      <webElementGuid>69fcd830-8ff8-4504-9e85-82f8a1d83652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Picture of Simple Computer</value>
      <webElementGuid>49520d03-b40f-4d1b-b7b6-ffd86b6be03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Picture of Simple Computer</value>
      <webElementGuid>f5cbc5df-ee9a-4ef7-b4b0-ca63543d407d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-details-form&quot;)/div[1]/div[@class=&quot;product-essential&quot;]/div[@class=&quot;gallery&quot;]/div[@class=&quot;picture-thumbs&quot;]/div[1]/a[@class=&quot;thumb-popup-link&quot;]/img[1]</value>
      <webElementGuid>c57fa0ce-f488-4fa0-a7b7-3bce04d8c237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div/div[2]/div/a[2]/img</value>
      <webElementGuid>5c83e4c6-05e0-411e-9b91-ed77b013b437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Picture of Simple Computer'])[3]</value>
      <webElementGuid>840e1a4b-7d44-4665-a321-d58e9d6713af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>07f283ef-8dec-480f-90a0-52290fb0dc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://demowebshop.tricentis.com/content/images/thumbs/0000205_simple-computer_70.jpeg' and @alt = 'Picture of Simple Computer' and @title = 'Picture of Simple Computer']</value>
      <webElementGuid>10f58723-7a9f-4b7a-bcd8-1b49f3a5572d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
