<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Image Viewer_product_attribute_75_8_35</name>
   <tag></tag>
   <elementGuidId>394b285b-e188-4c29-a510-7268699da374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_75_8_35_108']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_75_8_35_108</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>730e2eb5-e085-4f5e-9594-8f0f51af1833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_75_8_35_108</value>
      <webElementGuid>7a5a3f05-99b4-43fa-aa60-d6b49cbd1e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3c0f9889-a95f-424a-8b97-34333d6cdc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_75_8_35</value>
      <webElementGuid>56ce1ce2-eb3e-4d51-965b-11d6996b8eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>108</value>
      <webElementGuid>5d77a938-e382-4e39-ada2-8bc4823b2755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_75_8_35_108&quot;)</value>
      <webElementGuid>2473d365-41b7-4534-9a13-a52bfbc00b10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_75_8_35_108']</value>
      <webElementGuid>82ec47f5-4a03-4e37-9662-a8c0dc84a319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd[4]/ul/li[2]/input</value>
      <webElementGuid>bce3e454-de2d-4c99-9216-d3c1c309dd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[4]/ul/li[2]/input</value>
      <webElementGuid>1831105e-e231-4ecf-af41-feefc0edee0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_75_8_35_108' and @type = 'checkbox' and @name = 'product_attribute_75_8_35']</value>
      <webElementGuid>343d05a0-8447-467e-adc2-6f6d6a7c1924</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
