<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Software_product_attribute_75_8_35</name>
   <tag></tag>
   <elementGuidId>adc1b211-d8be-40ca-a717-c1a8e9e9554d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_75_8_35_107']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_75_8_35_107</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd5bea89-2149-45d7-8570-a20510558ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_75_8_35_107</value>
      <webElementGuid>7ec7a94c-5425-451f-bff3-e98a9270568c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>aae3e39f-2e17-4055-9db4-c9524f2bb4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_75_8_35</value>
      <webElementGuid>1d349f66-a401-4583-bc82-ebb3277cc8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>107</value>
      <webElementGuid>5474a963-abbd-4a5e-a730-eb03d95d2773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_75_8_35_107&quot;)</value>
      <webElementGuid>0e271fcd-a8c8-4069-ab4b-cbdcf41d6a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_75_8_35_107']</value>
      <webElementGuid>2084ff69-8c5f-485d-855d-1e5a00a5eaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd[4]/ul/li/input</value>
      <webElementGuid>7f538fe4-0bc9-4d93-917f-e119cb3ea206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[4]/ul/li/input</value>
      <webElementGuid>6ddbdf91-1214-4d6d-bfac-5c298941429c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_75_8_35_107' and @type = 'checkbox' and @name = 'product_attribute_75_8_35']</value>
      <webElementGuid>a1dd1265-2f34-407d-940a-161609248a42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
