<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__product_attribute_75_5_31</name>
   <tag></tag>
   <elementGuidId>5cf6fe45-816a-42fb-a27f-5c7ee63facc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_75_5_31_96']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_75_5_31_96</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c213a0c-bef5-4c27-9ef5-6fe51935301c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_75_5_31_96</value>
      <webElementGuid>153613dd-edb6-43db-94bb-f1d0df43899e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f572527f-e397-44b6-bf4e-de3c9c343db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_75_5_31</value>
      <webElementGuid>dd44e9fe-6ed7-4d77-824d-a09d55cf2b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>96</value>
      <webElementGuid>056c9c7f-d7d6-4a7f-9176-b0b2f03a30e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_75_5_31_96&quot;)</value>
      <webElementGuid>418192b5-4c32-4bf7-afa5-d1ad608f850c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_75_5_31_96']</value>
      <webElementGuid>d13f44f3-f640-46e5-b7c8-1ab4a0d9772d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd/ul/li/input</value>
      <webElementGuid>b8b21552-4322-4aea-bb6a-8cd5ce04f3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>25c47af4-96e6-4934-8e06-eb1d7dd4d7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_75_5_31_96' and @type = 'radio' and @name = 'product_attribute_75_5_31']</value>
      <webElementGuid>49d45472-72cc-4b89-a3f8-427e1cf53b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
