<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Excellent_add-review</name>
   <tag></tag>
   <elementGuidId>e95c030f-0ec5-4f4d-b1f5-0ae26fa9e325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='add-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;add-review&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>161cf5ee-9ed8-44ec-b99d-8c8eaa1a4cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6e6f5bb2-62f1-406e-b5f4-741c85aa00f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add-review</value>
      <webElementGuid>2a3b22ec-4995-4454-a380-957b35bc2ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-1 write-product-review-button</value>
      <webElementGuid>48da1283-030d-4a85-aa2e-0a5be930f979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit review</value>
      <webElementGuid>8c0b5270-1ed8-4d35-809a-412a2a4904e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-form&quot;)/form[1]/div[@class=&quot;buttons&quot;]/input[@class=&quot;button-1 write-product-review-button&quot;]</value>
      <webElementGuid>65141f8e-d6ed-4917-9f35-3d879021c09d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='add-review']</value>
      <webElementGuid>da47bd32-f868-450e-8ac4-bd2aa7f84032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/form/div[3]/input</value>
      <webElementGuid>4eafd521-c8c6-49fa-a7f2-42936415731b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>0a4295c1-175a-4e11-841e-f7d57ddf09cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'add-review']</value>
      <webElementGuid>bf879ef6-3362-49e3-bec4-295b692b3443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
