<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Review title_AddProductReview.Title</name>
   <tag></tag>
   <elementGuidId>e7c8c2cb-0a99-43f4-8629-12111571cf00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddProductReview_Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AddProductReview_Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49528336-10f7-41dd-8208-68b45fe29ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>review-title</value>
      <webElementGuid>0417674e-810a-4fbd-b3cd-bbc99baed0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddProductReview_Title</value>
      <webElementGuid>28faa0b8-474e-479e-bc0c-79f7aa586eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddProductReview.Title</value>
      <webElementGuid>122e937a-3b7a-4ac6-8aae-a3e3ae79d324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcb4c0f4-f779-4f71-a18b-27b370a4a1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddProductReview_Title&quot;)</value>
      <webElementGuid>5e978d94-16f4-4d0c-81f6-c49db25c208f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddProductReview_Title']</value>
      <webElementGuid>d08ae845-6aec-4f36-a269-2e1162d22976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/form/div[2]/div/input</value>
      <webElementGuid>78f5b58b-20b1-4a4b-bbe7-d35ed860dc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e436757c-cd0c-496f-938e-56fc5318210d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddProductReview_Title' and @name = 'AddProductReview.Title' and @type = 'text']</value>
      <webElementGuid>fed6615a-c66a-43fe-89ad-cb5b0cebf93d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
