<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Review text_AddProductReview.ReviewText</name>
   <tag></tag>
   <elementGuidId>ad8939eb-3347-4227-99ff-1e9801618497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='AddProductReview_ReviewText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AddProductReview_ReviewText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a6d24428-19d4-4444-8041-ed06ed511c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>review-text</value>
      <webElementGuid>b3d0958b-bc0b-4efd-90f1-a4158418e4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>93e1dd33-661b-49e2-9cca-a8ecc2b746d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddProductReview_ReviewText</value>
      <webElementGuid>bddd48ac-e217-4c91-8813-147b1ce18695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddProductReview.ReviewText</value>
      <webElementGuid>2ee15705-53c3-4ff1-8b8c-107516264b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d38fa48d-e969-4124-882d-930ddb15d021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddProductReview_ReviewText&quot;)</value>
      <webElementGuid>c1f63610-09d9-4836-b30e-050bb08d72b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='AddProductReview_ReviewText']</value>
      <webElementGuid>d412f9df-5ae5-4e67-8f75-4944b07e6d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/form/div[2]/div[2]/textarea</value>
      <webElementGuid>0f4a6291-8eff-47e3-89d4-d509d32d9495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>fba793e5-b14a-420e-95dc-a0bb42c71456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'AddProductReview_ReviewText' and @name = 'AddProductReview.ReviewText']</value>
      <webElementGuid>54dbd0e9-2a8f-4fff-b00f-2e68ecd496d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
