<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_BillingNewAddress.PhoneNumber</name>
   <tag></tag>
   <elementGuidId>4ba5cbd0-8791-434c-88e1-a8876d826a22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BillingNewAddress_PhoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BillingNewAddress_PhoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5460553-e36a-409c-990d-ed5bc8cf5d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>5aea2f89-b13d-4e79-9d30-8209c5073b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d0382ece-c5a8-4d70-b918-8fca3f01f52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Phone is required</value>
      <webElementGuid>fb3a5f4e-e932-427f-b74b-d0b6c326da14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BillingNewAddress_PhoneNumber</value>
      <webElementGuid>a3c39213-4ab0-4053-a490-f5aa8a66ece7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BillingNewAddress.PhoneNumber</value>
      <webElementGuid>a43a98d2-4de8-4f10-a0f9-c4ca958c3b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e61763ce-5c4c-441b-a26a-39672c24ada6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BillingNewAddress_PhoneNumber&quot;)</value>
      <webElementGuid>22557bde-700d-4ef2-9bfd-5ae5eb0bf890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BillingNewAddress_PhoneNumber']</value>
      <webElementGuid>35101c5b-18dd-4ded-bc4e-b16d4bd80922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing-new-address-form']/div/div/div/div[11]/input</value>
      <webElementGuid>12c5e2eb-bca5-4328-87ec-68d53358cb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>98597a05-a2b3-4dee-a2c7-d51d1d3f68ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BillingNewAddress_PhoneNumber' and @name = 'BillingNewAddress.PhoneNumber' and @type = 'text']</value>
      <webElementGuid>cb4ad3dd-80ed-4296-8d16-64943439f729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
