<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cash On Delivery (COD) (7.00)_paymentmethod</name>
   <tag></tag>
   <elementGuidId>fb0dcf6c-b043-4b72-8aa4-d32ccd3c0d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentmethod_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paymentmethod_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4a9a983-2d51-4add-944d-7ea272286036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentmethod_1</value>
      <webElementGuid>31bfd7a1-8843-4ef7-9ae3-33bdb4e6796e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a3b3e2df-24df-48cf-9b6c-bbf873304239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentmethod</value>
      <webElementGuid>9b4dd2ba-a73e-44c1-8b1c-ae1da174b66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Payments.CheckMoneyOrder</value>
      <webElementGuid>941755ec-aa28-4987-9e83-262ab587baf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentmethod_1&quot;)</value>
      <webElementGuid>65a47ed9-22b0-409a-8c8d-fc7b5852a85e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentmethod_1']</value>
      <webElementGuid>fdf8576a-97aa-4563-9515-06e3e2412cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-method-load']/div/div/ul/li[2]/div/div[2]/input</value>
      <webElementGuid>e8be71ac-f493-485b-8e52-63e531dafa03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[2]/input</value>
      <webElementGuid>aa0723ae-f796-4c64-8060-4e44a9ab02dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'paymentmethod_1' and @type = 'radio' and @name = 'paymentmethod']</value>
      <webElementGuid>cb870ddb-5d0d-44f6-8718-a91bf02318c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
