<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fax number_PickUpInStore</name>
   <tag></tag>
   <elementGuidId>6ece1ead-d9aa-4618-b112-ebb0d470b40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PickUpInStore']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PickUpInStore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81b31995-f024-4064-a9fc-1460c8a31927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PickUpInStore</value>
      <webElementGuid>c2566f8d-e749-4470-9a54-59f1ef90dde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PickUpInStore</value>
      <webElementGuid>aae50d88-b0b5-4b76-8b63-84d04c636ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Shipping.togglePickUpInStore(this)</value>
      <webElementGuid>3c9f273c-f376-4e4a-b095-40237f091601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>94ada0d2-2c8e-4a64-90bc-f7e03e2db994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dbf86eb2-5a59-4113-8ec1-42c6e0953e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PickUpInStore&quot;)</value>
      <webElementGuid>170648da-6d9e-4c4c-95c9-636cf40d5f3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PickUpInStore']</value>
      <webElementGuid>dadc1beb-b89c-4b21-bb98-a7c4ff95d7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-load']/div/div[2]/p/input</value>
      <webElementGuid>0556b8a6-a6e7-4103-b0c3-6d9b8472f2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>9393c2e9-dd6f-4793-bf64-b8c7d5380cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PickUpInStore' and @name = 'PickUpInStore' and @type = 'checkbox']</value>
      <webElementGuid>2c56f07a-c1cb-4d94-8596-44f41aef4065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
