<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1000.00</name>
   <tag></tag>
   <elementGuidId>274dc2a4-1bc6-47c3-85f0-e1a664df1de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by price'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.PriceRange</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>647b919d-746a-4ba2-8bd4-3b1335a15ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PriceRange</value>
      <webElementGuid>e320477a-a810-498f-8117-a7d68c28aa42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1000.00</value>
      <webElementGuid>55ad11aa-20a2-40f3-ab2b-8e5d340c270d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;master-wrapper-main&quot;]/div[@class=&quot;center-2&quot;]/div[@class=&quot;page category-page&quot;]/div[@class=&quot;page-body&quot;]/div[@class=&quot;product-filters-wrapper&quot;]/div[@class=&quot;product-filters price-range-filter&quot;]/div[@class=&quot;filter-content&quot;]/ul[@class=&quot;price-range-selector&quot;]/li[1]/a[1]/span[@class=&quot;PriceRange&quot;]</value>
      <webElementGuid>9e664241-a9da-4853-88ca-476f98b12df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by price'])[1]/following::span[1]</value>
      <webElementGuid>2f66750a-5448-4d22-9006-ad82a2c0871b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1000.00']/parent::*</value>
      <webElementGuid>52b647d6-1cb9-4da0-8d9b-8fe1ffdcee90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span</value>
      <webElementGuid>70138c29-4082-48e1-9ef7-48ff80dd1b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1000.00' or . = '1000.00')]</value>
      <webElementGuid>52dd5b8f-43cc-4a6c-9f71-5a4639b7766a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
