<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I agree with the terms of service and_f529a0</name>
   <tag></tag>
   <elementGuidId>df1617a3-c3e3-45c5-ad26-985ba25e5457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termsofservice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#termsofservice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1b88273-be73-413b-bfd1-2042cf70307e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termsofservice</value>
      <webElementGuid>8e1f3028-9d7b-455a-a6f1-b7dc30037792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cf7e978a-1515-404d-8905-32552f47ce78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsofservice</value>
      <webElementGuid>7438f3d0-37b2-48e3-bbf0-74bc79d7490e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsofservice&quot;)</value>
      <webElementGuid>3ddbab64-15bc-4bdc-9bed-5226d622fe00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termsofservice']</value>
      <webElementGuid>08ed1629-0b20-46d8-8e8a-4810d3514198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>4d7448c3-7c6d-4d19-b802-b1525cda0867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termsofservice' and @type = 'checkbox' and @name = 'termsofservice']</value>
      <webElementGuid>ab96898d-b7e1-48c0-b766-143e04afacde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
